# Generated by Django 5.1.6 on 2025-06-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doador',
            name='senha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
