# Generated by Django 5.1.6 on 2025-06-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doador_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Básica', 'Básica'), ('Especial', 'Especial'), ('Miserabilidade', 'Miserabilidade'), ('Natal', 'Natal')], max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
    ]
