# Generated by Django 5.1.6 on 2025-06-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cesta_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='doador',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
