# Generated by Django 5.1.6 on 2025-06-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_alimento_nome_alter_doador_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doacao',
            name='tipo',
            field=models.CharField(default='outro', max_length=20),
        ),
        migrations.AddField(
            model_name='doacao',
            name='unidade',
            field=models.CharField(default='unidade', max_length=20),
        ),
    ]
