# Generated by Django 5.1.6 on 2025-06-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_doacao_data_validade_doacao_tipo_doacao_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='unidade',
        ),
        migrations.AddField(
            model_name='alimento',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='tipo',
            field=models.CharField(default='outro', max_length=20),
        ),
        migrations.AddField(
            model_name='alimento',
            name='unidade',
            field=models.CharField(default='unidade', max_length=20),
        ),
    ]
