# Generated by Django 5.1.6 on 2025-06-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_doacao_data_validade_remove_doacao_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesta',
            name='tipo',
            field=models.CharField(choices=[('Cesta Padrão', 'Cesta Padrão'), ('Cesta Família com mais crianças', 'Cesta Família com mais crianças'), ('Cesta Família em estado de miserabilidade', 'Cesta Família em estado de miserabilidade'), ('Cesta de Natal', 'Cesta de Natal')], max_length=100),
        ),
    ]
